-- [[ Setting options ]]
-- See `:help vim.opt`
-- For more options, you can see `:help option-list`
vim.opt.termguicolors = true
vim.opt.guifont = "JetBrains Mono,Symbols Nerd Font Mono:h14.2"
vim.opt.background = "dark"
vim.opt.virtualedit = "block"
vim.opt.laststatus = 3
vim.opt.cmdheight = 1
vim.opt.showmode = false
vim.opt.clipboard = "unnamedplus"
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.cursorline = true
vim.opt.mouse = "a"
vim.opt.smartindent = true
vim.opt.autoindent = true
vim.opt.breakindent = true
vim.opt.undofile = true
vim.opt.expandtab = true
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.scrolloff = 2
vim.opt.updatetime = 250
vim.opt.signcolumn = "yes"
vim.opt.completeopt = "menu,menuone,noselect"
vim.opt.backup = false
vim.opt.conceallevel = 0
vim.opt.pumheight = 10
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.timeoutlen = 300
vim.opt.wrap = true
vim.opt.colorcolumn = "80"
vim.opt.whichwrap = "b,s,<,>,[,]"
vim.opt.winbar = "%n %m%F"
