#!/usr/bin/env bash

case $BLOCK_BUTTON in
  3) wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle ;;  # right click, mute/unmute
  4) wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%- ;; # swipe down, decrease
  5) wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+ ;; # swipe up, increase
esac

# Input string
input_string=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)

# Extracting volume value from the input string using regex
volume=$(echo "$input_string" | grep -oP '(?<=Volume: )\d+(\.\d+)?')

# Check if the input string contains "[MUTED]"
if echo "$input_string" | grep -q '\[MUTED\]'; then
    muted_status="[MUTED]"
else
    muted_status=""
fi

# Convert volume to percentage and remove trailing zeros
percentage=$(awk -v vol="$volume" 'BEGIN { printf "%.0f\n", vol * 100 }')

echo $LABEL$percentage%$muted_status"
echo $LABEL$percentage%$muted_status"
