live_config_reload = true

[colors.bright]
black =    '0x32302f'
red =      '0xea6962'
green =    '0xa9b665'
yellow =   '0xd8a657'
blue =     '0x7daea3'
magenta =  '0xd3869b'
cyan =     '0x89b482'
white =    '0xd4be98'

[colors.normal]
black =    '0x32302f'
red =      '0xea6962'
green =    '0xa9b665'
yellow =   '0xd8a657'
blue =     '0x7daea3'
magenta =  '0xd3869b'
cyan =     '0x89b482'
white =    '0xd4be98'

[colors.primary]
background =  '0x282828'
foreground =  '0xd4be98'

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.glyph_offset]
x = 0
y = -1

[font.offset]
x = 0
y = 0

[font.normal]
family = "JetBrains Mono"


[scrolling]
history = 10000
multiplier = 3

